FROM golang:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Just a dummy command to keep the container running
# this way we can exec into the container for our development flow
CMD ["tail", "-f", "/dev/null"]